sudo: required
services:
  - docker

before_install:
  - docker build -t matthewjury4/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true matthewjury4/docker-react npm run test

language: generic

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-088951536095"
  bucket_path: "resources/environments/e-4myeyz3v82/"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"