sudo: required
services:
  - docker

before_install:
  - docker build -t MatthewJury/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true MatthewJury/docker-react npm run test

language: generic